import { Injectable, computed, effect, signal } from '@angular/core';

export type Language = 'en' | 'ar';

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.shop': 'Shop',
    'nav.women': 'Women',
    'nav.men': 'Men',
    'nav.accessories': 'Accessories',
    'nav.admin': 'Admin',
    'nav.cart': 'Bag',
    'nav.account': 'Account',
    'nav.logout': 'Logout',
    'nav.login': 'Login',
    'nav.language': 'العربية',
    'nav.dark': 'Dark',
    'nav.light': 'Light',
    'footer.description': 'Premium fashion commerce built around fast buying, confident checkout, and adaptive recommendations.',
    'footer.secure': 'Secure checkout',
    'footer.shipping': 'Free shipping over $150',
    'footer.returns': 'Easy returns',
    'footer.shop': 'Shop',
    'footer.allProducts': 'All products',
    'footer.support': 'Support',
    'footer.payments': 'COD and Stripe-ready payments',
    'footer.email': 'Mock email notifications enabled',
    'auth.account': 'Veloura Account',
    'auth.createProfile': 'Create your profile',
    'auth.welcomeBack': 'Welcome back',
    'auth.subtitle': 'Fast checkout, saved orders, personalized picks, and provider access in one secure account.',
    'auth.secure': 'Secure',
    'auth.jwt': 'JWT sessions',
    'auth.instant': 'Instant',
    'auth.emailCode': 'Email code',
    'auth.ready': 'Ready',
    'auth.googleAuth': 'Google auth',
    'auth.client': 'Client',
    'auth.provider': 'Provider',
    'auth.email': 'Email',
    'auth.code': 'Code',
    'auth.google': 'Continue with Google',
    'auth.or': 'or',
    'auth.fullName': 'Full name',
    'auth.phone': 'Phone optional',
    'auth.company': 'Company name',
    'auth.website': 'Website',
    'auth.password': 'Password',
    'auth.adminCode': 'Admin code optional',
    'auth.sixCode': '6-digit code',
    'auth.sendCode': 'Send code',
    'auth.resend': 'Resend',
    'auth.mockCode': 'Verification code',
    'auth.mockHint': 'Email is mocked right now, so the code is filled automatically.',
    'auth.wait': 'Please wait...',
    'auth.verifyCreate': 'Verify & create account',
    'auth.verifyLogin': 'Verify & login',
    'auth.createAccount': 'Create account',
    'auth.login': 'Login',
    'auth.haveAccount': 'Already have an account?',
    'auth.newHere': 'New here?',
    'auth.addEmailName': 'Add your email and name first',
    'auth.codeSent': 'Verification code sent',
    'auth.codeReady': 'Verification code ready',
    'auth.couldNotSend': 'Could not send code',
    'auth.sendCodeFirst': 'Send a code first',
    'auth.enterCode': 'Enter the 6-digit code',
    'auth.invalidCode': 'Invalid code',
    'auth.authFailed': 'Authentication failed',
    'auth.signedIn': 'Signed in successfully',
    'auth.cartRetry': 'Signed in. Cart sync will retry from your bag.',
    'auth.googleNeedsConfig': 'Google sign-in needs GOOGLE_CLIENT_ID before launch',
    'auth.googleCredential': 'Google did not return a credential',
    'auth.googleFailed': 'Google sign-in failed',
    'auth.googleLoadFailed': 'Could not load Google sign-in',
    'adminUsers.kicker': 'Users CRUD',
    'adminUsers.title': 'Clients & Providers',
    'adminUsers.subtitle': 'Manage buyers, supplier accounts, admin access, status, and onboarding data from one place.',
    'adminUsers.new': 'New user',
    'adminUsers.clients': 'Clients',
    'adminUsers.providers': 'Providers',
    'adminUsers.active': 'Active',
    'adminUsers.disabled': 'Disabled',
    'adminUsers.search': 'Search users',
    'adminUsers.allTypes': 'All types',
    'adminUsers.allRoles': 'All roles',
    'adminUsers.users': 'Users',
    'adminUsers.admins': 'Admins',
    'adminUsers.allStatus': 'All status',
    'adminUsers.inactive': 'Disabled',
    'adminUsers.found': 'users found',
    'adminUsers.apply': 'Apply filters',
    'adminUsers.user': 'User',
    'adminUsers.type': 'Type',
    'adminUsers.providerProfile': 'Provider profile',
    'adminUsers.role': 'Role',
    'adminUsers.status': 'Status',
    'adminUsers.auth': 'Auth',
    'adminUsers.joined': 'Joined',
    'adminUsers.actions': 'Actions',
    'adminUsers.buyer': 'Buyer account',
    'adminUsers.edit': 'Edit',
    'adminUsers.disable': 'Disable',
    'adminUsers.empty': 'No users match these filters.',
    'adminUsers.account': 'Account',
    'adminUsers.editUser': 'Edit user',
    'adminUsers.createUser': 'Create user',
    'adminUsers.clear': 'Clear',
    'adminUsers.newPassword': 'New password optional',
    'adminUsers.tempPassword': 'Temporary password',
    'adminUsers.userRole': 'User',
    'adminUsers.adminRole': 'Admin',
    'adminUsers.pending': 'Pending',
    'adminUsers.approved': 'Approved',
    'adminUsers.rejected': 'Rejected',
    'adminUsers.activeAccount': 'Active account',
    'adminUsers.saving': 'Saving...',
    'adminUsers.save': 'Save user',
    'adminUsers.loadError': 'Could not load users',
    'adminUsers.saved': 'User saved',
    'adminUsers.saveError': 'Could not save user',
    'adminUsers.disableConfirm': 'Disable',
    'adminUsers.disabledToast': 'User disabled',
    'adminUsers.disableError': 'Could not disable user'
  },
  ar: {
    'nav.shop': 'المتجر',
    'nav.women': 'نساء',
    'nav.men': 'رجال',
    'nav.accessories': 'إكسسوارات',
    'nav.admin': 'لوحة التحكم',
    'nav.cart': 'السلة',
    'nav.account': 'الحساب',
    'nav.logout': 'خروج',
    'nav.login': 'دخول',
    'nav.language': 'English',
    'nav.dark': 'داكن',
    'nav.light': 'فاتح',
    'footer.description': 'منصة أزياء فاخرة مصممة للشراء السريع، والدفع الواضح، والترشيحات الذكية.',
    'footer.secure': 'دفع آمن',
    'footer.shipping': 'شحن مجاني للطلبات فوق 150 دولار',
    'footer.returns': 'إرجاع سهل',
    'footer.shop': 'المتجر',
    'footer.allProducts': 'كل المنتجات',
    'footer.support': 'الدعم',
    'footer.payments': 'الدفع عند الاستلام وتجهيز Stripe',
    'footer.email': 'إشعارات البريد التجريبية مفعلة',
    'auth.account': 'حساب Veloura',
    'auth.createProfile': 'إنشاء حساب جديد',
    'auth.welcomeBack': 'أهلًا بعودتك',
    'auth.subtitle': 'دفع أسرع، طلبات محفوظة، ترشيحات شخصية، ووصول للموردين في حساب آمن واحد.',
    'auth.secure': 'آمن',
    'auth.jwt': 'جلسات JWT',
    'auth.instant': 'فوري',
    'auth.emailCode': 'كود البريد',
    'auth.ready': 'جاهز',
    'auth.googleAuth': 'دخول Google',
    'auth.client': 'عميل',
    'auth.provider': 'مورد',
    'auth.email': 'البريد الإلكتروني',
    'auth.code': 'كود تأكيد',
    'auth.google': 'المتابعة باستخدام Google',
    'auth.or': 'أو',
    'auth.fullName': 'الاسم الكامل',
    'auth.phone': 'رقم الهاتف اختياري',
    'auth.company': 'اسم الشركة',
    'auth.website': 'الموقع الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.adminCode': 'كود الأدمن اختياري',
    'auth.sixCode': 'كود من 6 أرقام',
    'auth.sendCode': 'إرسال الكود',
    'auth.resend': 'إعادة الإرسال',
    'auth.mockCode': 'كود التأكيد',
    'auth.mockHint': 'البريد الإلكتروني تجريبي الآن، لذلك تم ملء الكود تلقائيًا.',
    'auth.wait': 'برجاء الانتظار...',
    'auth.verifyCreate': 'تأكيد وإنشاء الحساب',
    'auth.verifyLogin': 'تأكيد الدخول',
    'auth.createAccount': 'إنشاء الحساب',
    'auth.login': 'دخول',
    'auth.haveAccount': 'لديك حساب بالفعل؟',
    'auth.newHere': 'مستخدم جديد؟',
    'auth.addEmailName': 'اكتب الاسم والبريد الإلكتروني أولًا',
    'auth.codeSent': 'تم إرسال كود التأكيد',
    'auth.codeReady': 'كود التأكيد جاهز',
    'auth.couldNotSend': 'تعذر إرسال الكود',
    'auth.sendCodeFirst': 'أرسل الكود أولًا',
    'auth.enterCode': 'اكتب كود التأكيد المكون من 6 أرقام',
    'auth.invalidCode': 'كود غير صحيح',
    'auth.authFailed': 'فشل تسجيل الدخول',
    'auth.signedIn': 'تم تسجيل الدخول بنجاح',
    'auth.cartRetry': 'تم الدخول. ستتم مزامنة السلة لاحقًا.',
    'auth.googleNeedsConfig': 'تسجيل Google يحتاج GOOGLE_CLIENT_ID قبل الإطلاق',
    'auth.googleCredential': 'Google لم يرجع بيانات الدخول',
    'auth.googleFailed': 'فشل تسجيل الدخول بـ Google',
    'auth.googleLoadFailed': 'تعذر تحميل تسجيل Google',
    'adminUsers.kicker': 'إدارة المستخدمين',
    'adminUsers.title': 'العملاء والموردون',
    'adminUsers.subtitle': 'إدارة المشترين، حسابات الموردين، صلاحيات الأدمن، وحالة الحساب من مكان واحد.',
    'adminUsers.new': 'مستخدم جديد',
    'adminUsers.clients': 'العملاء',
    'adminUsers.providers': 'الموردون',
    'adminUsers.active': 'نشط',
    'adminUsers.disabled': 'معطل',
    'adminUsers.search': 'ابحث عن مستخدم',
    'adminUsers.allTypes': 'كل الأنواع',
    'adminUsers.allRoles': 'كل الصلاحيات',
    'adminUsers.users': 'المستخدمون',
    'adminUsers.admins': 'الأدمن',
    'adminUsers.allStatus': 'كل الحالات',
    'adminUsers.inactive': 'معطل',
    'adminUsers.found': 'مستخدم',
    'adminUsers.apply': 'تطبيق الفلاتر',
    'adminUsers.user': 'المستخدم',
    'adminUsers.type': 'النوع',
    'adminUsers.providerProfile': 'بيانات المورد',
    'adminUsers.role': 'الصلاحية',
    'adminUsers.status': 'الحالة',
    'adminUsers.auth': 'طريقة الدخول',
    'adminUsers.joined': 'تاريخ الانضمام',
    'adminUsers.actions': 'إجراءات',
    'adminUsers.buyer': 'حساب مشتري',
    'adminUsers.edit': 'تعديل',
    'adminUsers.disable': 'تعطيل',
    'adminUsers.empty': 'لا يوجد مستخدمون مطابقون للفلاتر.',
    'adminUsers.account': 'الحساب',
    'adminUsers.editUser': 'تعديل مستخدم',
    'adminUsers.createUser': 'إنشاء مستخدم',
    'adminUsers.clear': 'مسح',
    'adminUsers.newPassword': 'كلمة مرور جديدة اختيارية',
    'adminUsers.tempPassword': 'كلمة مرور مؤقتة',
    'adminUsers.userRole': 'مستخدم',
    'adminUsers.adminRole': 'أدمن',
    'adminUsers.pending': 'قيد المراجعة',
    'adminUsers.approved': 'مقبول',
    'adminUsers.rejected': 'مرفوض',
    'adminUsers.activeAccount': 'الحساب نشط',
    'adminUsers.saving': 'جاري الحفظ...',
    'adminUsers.save': 'حفظ المستخدم',
    'adminUsers.loadError': 'تعذر تحميل المستخدمين',
    'adminUsers.saved': 'تم حفظ المستخدم',
    'adminUsers.saveError': 'تعذر حفظ المستخدم',
    'adminUsers.disableConfirm': 'تعطيل',
    'adminUsers.disabledToast': 'تم تعطيل المستخدم',
    'adminUsers.disableError': 'تعذر تعطيل المستخدم'
  }
};

@Injectable({ providedIn: 'root' })
export class LanguageService {
  private readonly key = 'veloura_language';
  readonly language = signal<Language>(this.readInitialLanguage());
  readonly isArabic = computed(() => this.language() === 'ar');
  readonly dir = computed(() => this.isArabic() ? 'rtl' : 'ltr');

  constructor() {
    effect(() => {
      const language = this.language();
      localStorage.setItem(this.key, language);
      document.documentElement.lang = language;
      document.documentElement.dir = this.dir();
    });
  }

  toggle() {
    this.language.set(this.isArabic() ? 'en' : 'ar');
  }

  t(key: string) {
    return translations[this.language()][key] || translations.en[key] || key;
  }

  private readInitialLanguage(): Language {
    const stored = localStorage.getItem(this.key);
    return stored === 'ar' || stored === 'en' ? stored : 'en';
  }
}
